# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'test_user', password: 'password')
User.create(username: 'demo_user', password: 'password')

Artist.create(name: 'No Doubt', author_id: 1)
Artist.create(name: 'Nirvana', author_id: 1)
Artist.create(name: 'Oasis', author_id: 1)

Album.create(title: 'Tragic Kingdom', author_id: 1, artist_id: 1, release_date: '1995-10-05', img_url: "https://upload.wikimedia.org/wikipedia/en/9/9d/No_Doubt_-_Tragic_Kingdom.png",)
Album.create(title: 'Nevermind', author_id: 1, artist_id: 2, release_date: '1991-09-24')
Album.create(title: "(What's the Story) Morning Glory?", author_id: 1, artist_id: 3, release_date: '1995-10-02')

Track.create(title: 'Spiderwebs', author_id: 1, artist_id: 1, album_id: 1, track_number: 1, genre: 'rock',
  lyrics: "You think that we connect\nThat the chemistry's correct\nYour words walk right through my ears\nPresuming I like what I hear\nAnd now I'm stuck in the web\nYou're spinning\nYou've got me for your prey\nSorry I'm not home right now\nI'm walking into spiderwebs\nSo leave a message\nAnd I'll call you back\nA likely story, but leave a message\nAnd I'll call you back\nYou're intruding on what's mine and\nYou're taking up my time\nDon't have the courage inside me\nTo tell you please let me be\nCommunication, a telephonic invasion\nI'm planning my escape\nSorry I'm not home right now\nI'm walking into spiderwebs\nSo leave a message\nAnd I'll call you back\nA likely story, but leave a message\nAnd I'll call you back\nAnd it's all your fault\nI screen my phone calls\nNo matter who calls\nI gotta scream my phone calls\nNow it's gone too deep\nYou wake me in my sleep\nMy dreams become nightmares\n'Cause you're ringing in my ears.\nSorry I'm not home right now\nI'm walking into spiderwebs\nSo leave a message\nAnd I'll call you back\nA likely story, but leave a message\nAnd I'll call you back\nAnd It's all your fault\nI screen my phone calls\nNo matter matter matter who calls\nI gotta scream my phone calls\nOh spider webs\nLeave a message and I'll call you back\nI'm walking in a spider webs\nSo leave a message and I'll call you back\nAnd It's all your fault\nI screen my phone calls\nNo matter matter matter who calls\nI gotta scream my phone calls\nIt's all your fault\nIt's all your fault\nNo matter who calls\nNo matter who calls\nI'm walking into spiderwebs\nSo leave a message\nAnd I'll call you back\nI'm walking into spiderwebs\nLeave a message\nAnd I'll call you back\nI'm walking into spiderwebs\nLeave a message\nAnd I'll call you back\nI'm walking into spiderwebs\nLeave a message\nAnd I'll call you back\nI'm walking into spiderwebs\nLeave a message\nAnd I'll call you back\nI'm walking into spiderwebs\nLeave a message\nAnd I'll call you back")
Track.create(title: 'Excuse Me Mr.', author_id: 1, artist_id: 1, album_id: 1, track_number: 2, genre: 'rock',
  lyrics: "[Verse 1]\nI'm like a beggar with no luck\nI'm holding signs up\nOn your street corner stops\nLike most you try not to see me\nYou stare straight ahead\nIgnore the responsibility\n\n[Pre-Chorus]\nExcuse me (Excuse me Mr)\nI've been waiting in line\nAnd I'd like to buy some of your time\nI'm very anxious, eager, willing\nWhat's your billing?\n\n[Chorus]\nSo please excuse me Mr\nYou've got things all wrong\nYou make it feel like a crime\nSo don't confuse me Mr\nI've known you too long\nAll I need is a little of your time\n\n[Verse 2]\nFor most love comes for free\nThey don't pay the high cost\nOf mental custody I'll pay bail for a guarantee\nPlease make space for me In the time yet to be\n\n[Pre-Chorus]\nExcuse me (Excuse me Mr)\nI've been waiting in line\nAnd I'd like to buy\nSome of your time\nI've been saving up my life\nWhat's your price?\n\n[Chorus]\n\n[Bridge]\nWhat should I do?\nI'm about to crack\nAnd there's a force\nThat comes over me\nIt's almost as if I'm tied to the tracks\nAnd I'm waiting for him\nTo rescue me\nThe funny thing is\nHe's not going to come\nHe's not going to find me\nThis is a matter of fact\nThe desire you lack\nThis is the way I guess it has to be\n\nA little of your time\nI need a little of your time\nPlease, a little of your time\n\n[Chorus]\n\n[Outro]\nI'm in line to buy time\nI'm in line to buy time")
Track.create(title: 'Just A Girl', author_id: 1, artist_id: 1, album_id: 1, track_number: 3, genre: 'rock',
  lyrics: "[Verse 1]\nTake this pink ribbon off my eyes\nI'm exposed, and it's no big surprise\nDon't you think I know exactly where I stand?\nThis world is forcing me to hold your hand\n\n[Chorus]\nCause I'm just a girl, oh little old me\nDon't let me out of your sight\nI'm just a girl, all pretty and petite\nSo don't let me have any rights\n\n[Post-Chorus]\nOh, I've had it up to here\n\n[Verse 2]\nThe moment that I step outside\nSo many reasons for me to run and hide\nI can't do the little things I hold so dear\nCause it's all those little things that I fear\n\n[Chorus]\nCause I'm just a girl, I'd rather not be\nCause they won't let me drive late at night\nI'm just a girl, guess I'm some kind of freak\nCause they all sit and stare with their eyes\nI'm just a girl, take a good look at me\nJust your typical prototype\n\n[Post-Chorus]\nOh, I've had it up to here\nOh, am I making myself clear?\n\n[Bridge]\nI'm just a girl\nI'm just a girl in the world\nThat's all that you'll let me be\n\n[Chorus]\nI'm just a girl, living in captivity\nYour rule of thumb makes me worrisome\nI'm just a girl, what's my destiny\nWhat I've succumbed to is making me numb\nI'm just a girl, my apologies\nWhat I've become is so burdensome\nI'm just a girl, lucky me\nTwiddle-dum, there's no comparison\n\n[Outro]\nOh, I've had it up to\nOh, I've had it up to\nOh, I've had it up to here")
